config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  get 'user/show'
  get 'user/new'

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'user#new'
  post '/signup', to: 'user#create'
  get '/index', to: 'user#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/settings', to: 'user#edit'
  get '/invite/:user_id', to: 'game#new', as: "invite"
  get '/accept/:user_id', to: 'game#create', as: "accept"
  
  resources :user do
    resources :friend_requests
    resources :friends
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friend_request
  has_many :friend

  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :update, :edit]
  before_action :correct_user, only: [:update, :edit]
  
  layout "application.html.erb"
  def show
    @active = Hash.new("")
    @active[:profile] = "active"
    @user = User.find(params[:id])
  end
  
  def index
    @active = Hash.new("")
    @active[:players] = "active"
    @user = User.paginate(page: params[:page])
  end
  
  def edit
    @user = User.find(params[:id])
    @active = Hash.new("new")
    @active[:settings] = "active"
    unless current_user?(@user)
      redirect_to edit_user_path(current_user)
    end   
  end
  
  def new
    @active = Hash.new("")
    @user = User.new
  end
  
  def create
    @active = Hash.new("")
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if current_user?(@user) and @user.update(user_params)
       redirect_to @user
    else
      @active = Hash.new("new")
      @active[:settings] = "active"
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy if admin_user?(@user)
    redirect_to index_path 
      
  end
 
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/user_helper.rb
module UserHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/user/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
	  
	  <%= render 'shared/error_message' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/user/index.html.erb
<h1>All users</h1>


<%= will_paginate @users %>

<ul class="users">
  <% @user.each do |u| %>
    <li class = "index">
      <%= gravatar_for u, size: 50 %>
      <%= link_to u.name, u, :class => "name" %>
       &nbsp;
      <% if !current_user?(u) && !u.friend_request.exists?(from_id: current_user.id) %>
        <%= link_to "friend", user_friend_requests_path(u), method: :post %>
       &nbsp;
     <% end %>
      <% if current_user.admin? && !current_user?(u) %>  
        <%= link_to "delete", u, method: :delete, data: {confirm: "Are You Sure?"} %>
    ` <% end %>
          </li>
  <% end %>
 
<%= will_paginate %>
</ul>

app/views/user/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-sm-5 signup">

    <%= form_for(@user, url: 'signup') do |f| %>
	  <%= render 'shared/error_message' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<div class = "row">
  <div class= "col-sm-3 user_info">
	  <h1><%= @user.name %></h1>
        <%= gravatar_for @user %> 
    <% if !current_user?(@user) && !@user.friend_request.exists?(from_id: current_user.id) %>
        <%= link_to "friend", user_friend_requests_path(@user), method: :post %>
     <% end %>
  </div>
        
  <% if current_user?(@user) %>
    
    <div class= "col-sm-4 requests">
	  <h3> Friend Requests</h3>
      <p> Sent to You </p>
        <ul class = "request">
        <% @user.friend_request.each do |request|%>
          <% sender = User.find(request.from_id) %>
          <li class = "list-group-item" > <%= link_to sender.name, sender, :class => "r_name" %>
                &nbsp;
               <%= link_to "accept", user_friends_path(sender), method: "post", :class => "r_accept" %>
               &nbsp;
               <%= link_to "decline", user_friend_request_path(sender), method: "delete", :class => "r_decline" %>
        <% end %>
        </ul>
                 
         <p> You Sent</p>        
        <ul class = "request">
        <% FriendRequest.where(from_id: @user.id).each do |sent|%>
          <% user = User.find(sent.user_id) %>
          <li class = "list-group-item" > <%= link_to user.name, user, :class => "r_name" %>
           &nbsp;
          <%= link_to "withdraw", user_friend_request_path(user), method: "delete", :class => "r_decline" %>
        <% end %>
        </ul>                
    </div>
        
    <div class= "col-sm-4 requests">
	  <h3> Friends</h3>
        <ul class = "request">
        <% @user.friend.each do |request|%>
          <% friend = User.find(request.friend_id) %>
          <li class = "list-group-item" > <%= link_to friend.name, friend, :class => "r_name" %>
                &nbsp;
               <%= link_to "remove", user_friend_path(friend), method: "delete", :class => "r_decline" %>
                &nbsp;
               <%= link_to "invite to game", invite_path(friend), :class => "r_accept" %>
        <% end %>
        </ul>    
  <% end %>
  </div>
</div>