config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  
  get 'user/show'
  get 'user/new'

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'user#new'
  post '/signup', to: 'user#create'
  get '/index', to: 'user#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/settings', to: 'user#edit'
  get '/invite/:user_id', to: 'game#new', as: "invite"
  get '/accept/:user_id', to: 'game#create', as: "accept"
  
  resources :user do
    resources :friend_requests
    resources :friends
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_gameBoard.html.erb
<canvas id="others" width="1000" height="80" style="border:1px solid #d3d3d3;" draggable='false'>
Your browser does not support the HTML5 canvas tag.</canvas>

<canvas id="myCanvas" width="1000" height="750" style="border:1px solid #d3d3d3;" draggable='false'>
Your browser does not support the HTML5 canvas tag.</canvas>

<canvas id="yours" width="1000" height="80" style="border:1px solid #d3d3d3;" draggable='false'>
Your browser does not support the HTML5 canvas tag.</canvas>
<script src="script.js"></script>

<p id="display"></p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Hive</a>
    </div>
    <ul class="nav navbar-nav">
        <li class= <%= @active[:home] %> ><%= link_to "Home", root_path %></li>
		<li class= <%= @active[:game] %> ><%= link_to "Find Game", root_path %></li>
		<li class= <%= @active[:players] %> ><%= link_to "Players", index_path %></li>
		<% if logged_in? %>
			<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class= <%= @active[:profile] %>><%= link_to "Profile", current_user %></li>
              <li class= <%= @active[:settings] %>><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
		<% else %>
			<li class="right_side"> <%= link_to "Login", login_path %> </li>
		<% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_we.html.erb
<div class="col-3 we_are">
		<ul class="we_are">
			<li>We Are</li>
			<li>Independent</li>
			<li>Strong</li>
			<li>HardWorking</li>
			<li>Devoted</li>
			<li>Able</li>
			<li>Confident</li>
			<li class="no_lower">Willed</li>
		</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PipaAssociation</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
      
    <script>  
    $(document).ready(function () {
        $('.dropdown-toggle').dropdown();
    });
    </script>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <div class = "msg">
        <p id = "friend-popup"></p>
        <a class = "r_accept" id="game_accept"></a>
      </div>
    <%= yield %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>